# Generated by Django 5.1.1 on 2024-09-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='start_date',
        ),
    ]
