# Generated by Django 5.1.1 on 2024-10-17 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_rename_end_date_leaverequest_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='date',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('maternity', 'Maternity Leave')], max_length=10),
        ),
    ]
